<?php
// Set page title
$pageTitle = "Picture Gallery";

// Add JavaScript for gallery
$additionalScripts = '<script src="/js/gallery.js" defer></script>';

// Include header
include '../includes/header.php';
?>

<div class="container">
    <h1>Picture Gallery</h1>
    
    <p>This page demonstrates a custom JavaScript picture gallery implementation with navigation controls.</p>
    
    <div class="gallery-container">
        <div class="main-image-container">
            <img id="mainImage" src="/images/gallery/gallery_image1.jpg" alt="Gallery Image 1" class="main-image" />
        </div>
        
        <div class="gallery-controls">
            <button id="prevButton" class="gallery-button">Previous</button>
            <button id="nextButton" class="gallery-button">Next</button>
        </div>
        
        <div class="thumbnails-container">
            <div class="thumbnails" id="thumbnailsContainer">
                <!-- Thumbnails will be dynamically generated by JavaScript -->
            </div>
        </div>
    </div>
    
    <div class="gallery-info">
        <h2>Gallery Information</h2>
        <p>This gallery demonstrates the following features:</p>
        <ul>
            <li>Custom JavaScript implementation (no jQuery or plugins)</li>
            <li>Navigation buttons for previous and next images</li>
            <li>Thumbnail navigation with active state indication</li>
            <li>Responsive design that adapts to different screen sizes</li>
            <li>Proper image organization with thumbnails and full-size versions</li>
        </ul>
    </div>
</div>

<style>
/* Additional styles specific to the gallery page */
.gallery-container {
    margin: 2rem 0;
}

.main-image-container {
    text-align: center;
    margin-bottom: 1rem;
    background-color: #f5f5f5;
    padding: 1rem;
    border-radius: 5px;
}

.main-image {
    max-width: 100%;
    max-height: 500px;
    border: 1px solid #ddd;
}

.gallery-controls {
    display: flex;
    justify-content: center;
    gap: 1rem;
    margin: 1rem 0;
}

.gallery-button {
    background-color: #005a87;
    color: white;
    border: none;
    padding: 0.5rem 1.5rem;
    border-radius: 3px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.gallery-button:hover {
    background-color: #003d5c;
}

.thumbnails-container {
    margin: 1.5rem 0;
}

.thumbnails {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    justify-content: center;
}

.thumbnail {
    width: 100px;
    height: 75px;
    object-fit: cover;
    border: 2px solid #ddd;
    cursor: pointer;
    transition: border-color 0.3s ease;
}

.thumbnail:hover {
    border-color: #005a87;
}

.thumbnail.active {
    border-color: #005a87;
    box-shadow: 0 0 5px rgba(0, 90, 135, 0.5);
}

.gallery-info {
    background-color: #f9f9f9;
    padding: 1.5rem;
    border-radius: 5px;
    margin-top: 2rem;
}

@media screen and (max-width: 768px) {
    .thumbnail {
        width: 80px;
        height: 60px;
    }
}

@media screen and (max-width: 480px) {
    .thumbnails {
        gap: 0.25rem;
    }
    
    .thumbnail {
        width: 60px;
        height: 45px;
    }
}
</style>

<?php
// Include footer
include '../includes/footer.php';
?>
